# Generated by Django 4.2.7 on 2023-12-05 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purifier', '0005_alter_employee_mobile_alter_employee_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to='customer_profiles/'),
        ),
    ]
