# Generated by Django 4.2.7 on 2023-12-15 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purifier', '0009_test_servicework'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='installed_product',
            field=models.ManyToManyField(to='purifier.product'),
        ),
    ]
