# Generated by Django 4.2.7 on 2023-12-16 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purifier', '0010_customer_installed_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='installed_product',
            field=models.ManyToManyField(blank=True, null=True, to='purifier.product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='purifier.category'),
        ),
    ]
