# Generated by Django 4.2.7 on 2023-12-26 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purifier', '0011_alter_customer_installed_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_serial',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='servicework',
            name='service_work_code',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='test',
            name='customer_code',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='purifier.customer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_code',
            field=models.CharField(blank=True, default=2, max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
