# Generated by Django 4.2.7 on 2023-12-27 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purifier', '0012_product_product_serial_servicework_service_work_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicework',
            name='product',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='purifier.product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='services',
            field=models.ManyToManyField(blank=True, null=True, to='purifier.service'),
        ),
        migrations.AlterField(
            model_name='servicework',
            name='comment_section',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='servicework',
            name='remark_section',
            field=models.TextField(blank=True, null=True),
        ),
    ]
