# Generated by Django 4.2.7 on 2023-12-27 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purifier', '0013_servicework_product_alter_product_services_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicework',
            name='product',
        ),
    ]
