# Generated by Django 4.2.7 on 2023-12-27 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purifier', '0014_remove_servicework_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicework',
            name='product',
            field=models.ForeignKey(default='5123f1cc-2f77-47fe-b52a-f0f829ae9fe2', on_delete=django.db.models.deletion.CASCADE, to='purifier.product'),
            preserve_default=False,
        ),
    ]
