# Generated by Django 5.0.1 on 2024-01-05 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purifier', '0017_rename_message_serviceassign_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='district',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='state',
        ),
    ]
