# Generated by Django 5.0.1 on 2024-01-05 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purifier', '0019_customer_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='location',
        ),
    ]
