# Generated by Django 5.0.1 on 2024-01-08 04:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purifier', '0021_alter_customer_installed_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceassign',
            name='notification',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='serviceassign',
            name='service',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='purifier.servicework'),
        ),
    ]
