# Generated by Django 5.0.1 on 2024-01-30 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purifier', '0023_servicework_status_alter_serviceassign_servicer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicework',
            name='service_name',
        ),
        migrations.AlterField(
            model_name='servicework',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('working', 'Working'), ('completed', 'Completed')], default='pending', max_length=30),
        ),
        migrations.AddField(
            model_name='servicework',
            name='service_name',
            field=models.ManyToManyField(to='purifier.service'),
        ),
    ]
