# Generated by Django 4.2 on 2023-08-31 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('myapp', '0003_createuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createuser',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='employee_groups', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='createuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='employee_user_permissions', to='auth.permission'),
        ),
    ]
