# Generated by Django 4.2 on 2023-08-31 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_createuser_groups_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createuser',
            name='confirm_password',
        ),
    ]
