# Generated by Django 4.2 on 2023-08-31 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_createuser_confirm_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signin',
            name='username',
            field=models.EmailField(max_length=50),
        ),
    ]
