# Generated by Django 4.2 on 2023-09-03 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_signin_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CreateUser',
        ),
    ]
