# Generated by Django 4.2 on 2023-09-04 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_delete_createuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SignIn',
        ),
        migrations.DeleteModel(
            name='SignUp',
        ),
    ]
