# Generated by Django 4.2 on 2023-09-06 09:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_customer_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('chalan_no', models.IntegerField(blank=True)),
            ],
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='customer_id',
            new_name='id',
        ),
        migrations.CreateModel(
            name='QuotationJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('length', models.IntegerField()),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('remarks', models.CharField(blank=True, max_length=700, null=True)),
                ('quantity', models.IntegerField()),
                ('attachment', models.FileField(upload_to='')),
                ('quotation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.quotation')),
            ],
        ),
        migrations.AddField(
            model_name='quotation',
            name='customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.customer'),
        ),
    ]
