# Generated by Django 4.2 on 2023-09-06 11:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_quotation_rename_customer_id_customer_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('machine_name', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('ready_to_work', 'Ready to work'), ('running', 'Running'), ('In maintanance', 'In Maintanace')], default='ready_to_work', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('estimate_duration', models.DurationField(blank=True, null=True)),
                ('completed_in', models.DurationField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='pending', max_length=30)),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.quotationjob')),
                ('machine_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.machine')),
            ],
        ),
    ]
