# Generated by Django 4.2 on 2023-09-14 09:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_machine_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='quotation',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('in_process', 'In Process'), ('ready_to_deliver', 'Ready to Deliver'), ('delivered_successfully', 'Delivered Successfully')], default='draft', max_length=50),
        ),
    ]
