# Generated by Django 4.2 on 2023-09-14 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_quotation_created_on_quotation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotationjob',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
