# Generated by Django 4.2 on 2023-09-15 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_alter_quotationjob_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotationjob',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
