# Generated by Django 4.2 on 2023-09-15 09:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_alter_quotationjob_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotationjob',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
