# Generated by Django 4.2 on 2023-10-06 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_employee_employeedesignation'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='designation',
            field=models.ForeignKey(default=22, on_delete=django.db.models.deletion.CASCADE, to='myapp.employeedesignation'),
            preserve_default=False,
        ),
    ]
