# Generated by Django 4.2 on 2023-10-12 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_employee_designation'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationjob',
            name='assigned_employee',
            field=models.ManyToManyField(blank=True, to='myapp.employee'),
        ),
    ]
