# Generated by Django 4.2 on 2023-10-17 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_remove_quotationjob_assigned_employee_jobassign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotationjob',
            name='height',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='quotationjob',
            name='length',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='quotationjob',
            name='width',
            field=models.FloatField(),
        ),
    ]
