# Generated by Django 4.2 on 2023-10-26 09:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_alter_quotationjob_height_alter_quotationjob_length_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SequentialCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('code_prefix', models.CharField(max_length=5)),
                ('code_digits', models.IntegerField()),
                ('code_suffix', models.CharField(blank=True, max_length=5, null=True)),
            ],
        ),
    ]
