# Generated by Django 4.2 on 2023-10-26 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_sequentialcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='sequential_code',
            field=models.CharField(default=0, editable=False, max_length=30, unique=True),
        ),
    ]
