# Generated by Django 4.2 on 2023-10-27 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_quotation_sequential_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sequentialcode',
            old_name='code_digits',
            new_name='code_size',
        ),
        migrations.AlterField(
            model_name='quotation',
            name='sequential_code',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='sequentialcode',
            name='code_prefix',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='sequentialcode',
            name='code_suffix',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
