# Generated by Django 4.2 on 2023-10-27 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_rename_code_digits_sequentialcode_code_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sequentialcode',
            name='code_of',
            field=models.CharField(choices=[('quotation', 'Quotation'), ('quotation_job', 'Quotation Job'), ('task', 'Task')], default=2, max_length=30),
            preserve_default=False,
        ),
    ]
