# Generated by Django 4.2 on 2023-11-03 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0028_sequentialcode_code_of'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationjob',
            name='sequential_code',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='sequential_code',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
