# Generated by Django 4.2 on 2023-11-14 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_quotationjob_sequential_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='sequential_code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='sequential_code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='quotationjob',
            name='sequential_code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
