# Generated by Django 4.2 on 2023-11-14 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0030_task_sequential_code_alter_quotation_sequential_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='sequential_code',
        ),
        migrations.AddField(
            model_name='task',
            name='operator_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.employee'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='machine_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.machine'),
        ),
    ]
