# Generated by Django 4.2 on 2023-11-14 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0031_remove_task_sequential_code_task_operator_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='sequential_code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
